# Generated by Django 5.1.6 on 2025-03-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol_usuario',
            field=models.CharField(choices=[('admin_general', 'Administrador General'), ('usuario', 'Usuario')], max_length=60),
        ),
    ]
